# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChangeAppLogo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChangeAppLogo
  pod "GCDWebServer", "~> 3.0"
  pod "YYModel"
  pod "SDWebImage"
  pod 'IQKeyboardManager'
  pod 'TZImagePickerController'
  pod 'MBProgressHUD'
end
