# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://gitee.com/wangguibin/my-pod-specs'

target 'ChangeAppLogo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChangeAppLogo
  pod 'WGBToolKit', '~> 0.1.3'
  pod "GCDWebServer", "~> 3.0"
  pod "YYModel"
  pod "SDWebImage"
  pod 'IQKeyboardManager'
  pod 'TZImagePickerController'
  pod 'MBProgressHUD'
end
