name: Build App

on:
  push:
    tags: '*.*.*'
    branches: [ main ]
    
  workflow_dispatch:
    

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        workspace: ChangeAppLogo/ChangeAppLogo.xcworkspace
        scheme: ChangeAppLogo
        configuration: Release
#     - name: Package Zip
#       run: |
#           export BUILD_DIR=$(xcodebuild -project ChangeAppLogo/ChangeAppLogo.xcodeproj -scheme ChangeAppLogo -configuration Release -showBuildSettings | grep -m 1 "BUILT_PRODUCTS_DIR" | grep -oEi "\/*.app" | head -1)
#           (cd "$BUILD_DIR" ; zip -r ChangeAppLogo.app.zip ./ChangeAppLogo.app)
#           cp "$BUILD_DIR/ChangeAppLogo.app.zip" .
          
#     - uses: actions/upload-artifact@v2
#       name: Upload artifacts
#       with:
#         name: ChangeAppLogo
#         path: ./ChangeAppLogo.app.zip
#     - name: Release
#       uses: softprops/action-gh-release@v1
#       if: startsWith(github.ref, 'refs/tags/')
#       with:
#         files: |
#             ChangeAppLogo.app.zip
#       env:
#         GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
    
