name: Build App

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        workspace: ChangeAppLogo/ChangeAppLogo.xcworkspace
        scheme: ChangeAppLogo
        configuration: Release
    - name: Package Zip
      run: |
          export BUILD_DIR=$(xcodebuild -workspace ChangeAppLogo/ChangeAppLogo.xcworkspace -scheme ChangeAppLogo -configuration Release -showBuildSettings  | grep -m 1 "BUILT_PRODUCTS_DIR" | grep -oEi "\/.*")
          (cd "$BUILD_DIR" ; zip -r ChangeAppLogo.app.zip ./ChangeAppLogo.app)
          cp "$BUILD_DIR/ChangeAppLogo.app.zip" .
    
